### ISSUE TITLE
Build/install issues on macOs 11 

### ISSUE THREAD

**Issue by HumanG33k** [Unvanquished/Unvanquished#1237]
I follow the readme.md

First this can be add i guess (i will) to the readme

With brew dependancies can be install quite easily. 

```bash
# Install needed dependancies 
brew install zlib gmp nettle curl SDL2 \
  GLEW libpng libjpeg webp Freetype \
  Lua openal-soft  libogg libvorbis  \
  ffmpeg2theora libopusenc

# Install optionnal dependancies
brew install ncurses libgeoip
```

At the cmake --build build -- -j4 step :
-j4 can be replace by something better see https://unix.stackexchange.com/questions/208568/how-to-determine-the-maximum-number-to-pass-to-make-j-option

Downloading dependencies from 'http://dl.unvanquished.net/deps/macosx64-4.tar.bz2' <= what exactly is download ?

Also this error occurs : 

```bash 
-- Found PythonInterp: /usr/bin/python (found version "2.7.16") 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named jinja2
CMake Error at daemon/cmake/DaemonCBSE.cmake:42 (message):
  Missing dependences for CBSE generation.  Please ensure you have python ?
  2, python-yaml, and python-jinja installed.

                               Use pip install -r src/utils/cbse/requirements.txt to install
Call Stack (most recent call first):
  CMakeLists.txt:119 (CBSE)

```

I guess this should add as build requirement.  And the output command is wrong on mac see below. 
```bash 
brew install python 
pip3 install -r src/utils/cbse/requirements.txt
```
But it not solve the error even with a rm on the build directory.

**Comment by illwieckz** [comment]
`pip3` is python3 as far as I know, so you install python3 variants of the requirement and python2 can't find them. Pip must be named `pip`.

**Comment by HumanG33k** [comment]
No there is no pip command. Only pip3

**Comment by slipher** [comment]
> http://dl.unvanquished.net/deps/macosx64-4.tar.bz2 <= what exactly is download ?

This contains pre-built binaries for Mac dependencies. You don't have to install most things with brew because they are in there. You may want to use GLEW from brew though - the prebuilt one is too old and doesn't work on MacOS Catalina (I'm currently working on a new dependencies package).

> But it not solve the error even with a rm on the build directory.

You can set the cmake variable `PYTHON_EXECUTABLE` if it is not using the version of Python that you want it to.

**Comment by HumanG33k** [comment]
@slipher works !!!

The command is : 
```bash 
cmake -H. -Bbuild -DPYTHON_EXECUTABLE:FILEPATH=/usr/local/bin/python3
```
I know python 2 is end of life but there is no way to test in the cmake recipe ? (not a cmake  expert)

After i did the : 
```bash 
cmake --build build -- -j4
```
And it fails as follow :

```bash
[ 51%] Built target sgame-native-exe
[ 51%] Building CXX object CMakeFiles/ROCKET_LIB.dir/libs/libRocket/Source/Controls/Lua/ElementFormControlSelect.cpp.o
[ 51%] Building CXX object CMakeFiles/ROCKET_LIB.dir/libs/libRocket/Source/Controls/Lua/ElementFormControlTextArea.cpp.o
[ 51%] Building CXX object CMakeFiles/ROCKET_LIB.dir/libs/libRocket/Source/Controls/Lua/ElementForm.cpp.o
[ 51%] Building CXX object CMakeFiles/ROCKET_LIB.dir/libs/libRocket/Source/Controls/Lua/ElementTabSet.cpp.o
[ 51%] Building CXX object CMakeFiles/ROCKET_LIB.dir/libs/libRocket/Source/Controls/Lua/LuaDataFormatter.cpp.o
[ 51%] Building CXX object CMakeFiles/ROCKET_LIB.dir/libs/libRocket/Source/Controls/Lua/LuaDataSource.cpp.o
[ 51%] Building CXX object CMakeFiles/ROCKET_LIB.dir/libs/libRocket/Source/Controls/Lua/SelectOptionsProxy.cpp.o
[ 52%] Linking CXX static library libROCKET_LIB.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libROCKET_LIB.a(precompiled.cpp.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libROCKET_LIB.a(precompiled.cpp.o) has no symbols
[ 52%] Built target ROCKET_LIB
```
looks related to #1219

**Comment by slipher** [comment]
Precompiled headers must be broken on Mac. Add `-DUSE_PRECOMPILED_HEADER=0` to your cmake command.

**Comment by HumanG33k** [comment]
I run following : 

```bash 
rm -rf build
cmake -H. -Bbuild -DPYTHON_EXECUTABLE:FILEPATH=/usr/local/bin/python3 -DUSE_PRECOMPILED_HEADER=0
```
output
```bash
-- git reported v0.51.1-103-g79df180a5
-- client
-- server
-- ttyclient
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/user/Projects/Unvanquished/build
```
And After 
```bash
cmake --build build -- -j4
```
but i get 

```bash 
[ 28%] Building CXX object daemon_build/CMakeFiles/engine-lib.dir/src/common/Color.cpp.o
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named jinja2
CMake Error at daemon/cmake/DaemonCBSE.cmake:42 (message):
  Missing dependences for CBSE generation.  Please ensure you have python ?
  2, python-yaml, and python-jinja installed.

                               Use pip install -r src/utils/cbse/requirements.txt to install
Call Stack (most recent call first):
  CMakeLists.txt:119 (CBSE)


-- Configuring incomplete, errors occurred!
See also "/Users/user/Projects/Unvanquished/build/nacl-vms/CMakeFiles/CMakeOutput.log".
See also "/Users/user/Projects/Unvanquished/build/nacl-vms/CMakeFiles/CMakeError.log".
make[2]: *** [nacl-vms-prefix/src/nacl-vms-stamp/nacl-vms-configure] Error 1
make[1]: *** [CMakeFiles/nacl-vms.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

```
Not sure i can add the python path option and how ? (i try it fail)

**Comment by slipher** [comment]
There isn't anyway to make it use a different Python for the CBSE and NaCl parts. So the easiest thing is to disable NaCl builds by setting the cmake option `BUILD_GAME_NACL` to 0.

**Comment by HumanG33k** [comment]
And : 

```bash 
cmake -H. -Bbuild -DPYTHON_EXECUTABLE:FILEPATH=/usr/local/bin/python3 -DUSE_PRECOMPILED_HEADER=0 -DBUILD_GAME_NACL=0
```
make it 

```bash
[ 99%] Built target client
[ 99%] Building CXX object CMakeFiles/cgame-native-exe.dir/daemon/src/engine/qcommon/q_unicode.cpp.o
[100%] Building CXX object CMakeFiles/cgame-native-dll.dir/daemon/src/engine/qcommon/q_math.cpp.o
[100%] Building CXX object CMakeFiles/cgame-native-dll.dir/daemon/src/engine/qcommon/q_shared.cpp.o
[100%] Building CXX object CMakeFiles/cgame-native-dll.dir/daemon/src/engine/qcommon/q_unicode.cpp.o
[100%] Linking CXX executable cgame-native-exe
[100%] Built target cgame-native-exe
[100%] Linking CXX shared module cgame-native-dll.so
[100%] Built target cgame-native-dll
```

**Comment by illwieckz** [comment]
I guess yes.

**Comment by HumanG33k** [comment]
I notice few things and they need to be investigate i think. ( i started the game before test package build )

 First when i try to retrieve 
```bash
./download-paks build/pkg 
Missing aria2c tool, fallback on HTTP download using curl…
Cache directory: build/pkg/.cache
Download directory: build/pkg
Starting HTTP download…
Downloading from: http://cdn.unvanquished.net/unvanquished_0.51.1/pkg
Downloading md5sums asto md5sums…
Downloading /Users/user/Projects/Unvanquished/build/pkg/.cache to …
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Downloaded.
Verifying md5sums integrity…
Successful.
Listed files:
Downloading missing or updated files…
Verifying files…
Errors found during verification. Re-downloading is recommended.
Cleaning-up cache…
Finished.
```
But curl is install.

After a 
```bash
brew install aria2
```
it works : 

```bash
Cache directory: build/pkg/.cache
Download directory: build/pkg
Starting BitTorrent download…
Downloading from: http://cdn.unvanquished.net
Downloading unvanquished_0.51.1.torrent /Users/user/Projects/Unvanquished/build/pkg/.cacheto …

11/28 17:43:57 [NOTICE] Downloading 1 item(s)
[#1b3e30 0B/0B CN:1 DL:0B]                                                                                                                                                                                                                                 
11/28 17:43:58 [NOTICE] Download complete: //Users/user/Projects/Unvanquished/build/pkg/.cache/unvanquished_0.51.1.torrent.tmp

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
1b3e30|OK  |   352KiB/s|//Users/user/Projects/Unvanquished/build/pkg/.cache/unvanquished_0.51.1.torrent.tmp

Status Legend:
(OK):download completed.
Downloaded.
Downloading assets…

11/28 17:43:58 [NOTICE] Downloading 1 item(s)

11/28 17:43:58 [ERROR] Exception caught while loading DHT routing table from /Users/user/.cache/aria2/dht.dat
Exception: [DHTRoutingTableDeserializer.cc:83] errorCode=1 Failed to load DHT routing table from /Users/user/.cache/aria2/dht.dat

11/28 17:43:58 [NOTICE] IPv4 DHT: listening on UDP port 6978

11/28 17:43:59 [ERROR] Checksum error detected. file=/Users/user/Projects/Unvanquished/build/pkg/.cache/unvanquished_0.51.1

11/28 17:43:59 [NOTICE] Allocating disk space. Use --file-allocation=none to disable it. See --file-allocation option in man page for more details.

11/28 17:43:59 [NOTICE] IPv4 BitTorrent: listening on TCP port 6991

11/28 17:43:59 [NOTICE] IPv6 BitTorrent: listening on TCP port 6991

11/28 17:43:59 [NOTICE] CUID#23 - Redirecting to https://webseed.unv.kangz.net/unv-launcher/unvanquished_0.51.1/pkg/map-thunder_1.3.2.dpk

11/28 17:43:59 [NOTICE] CUID#22 - Redirecting to https://webseed.unv.kangz.net/unv-launcher/unvanquished_0.51.1/pkg/res-legacy_0.51.dpk
[#7d4c1d 688KiB/456MiB(0%) CN:5 SD:0 DL:1.9MiB ETA:3m58s]                                                                                                                                                                                                  
11/28 17:44:00 [ERROR] CUID#22 - Download aborted. URI=http://webseed.unv.kangz.net/unv-launcher/unvanquished_0.51.1/pkg/res-legacy_0.51.dpk
Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://webseed.unv.kangz.net/unv-launcher/unvanquished_0.51.1/pkg/res-legacy_0.51.dpk
  -> [SocketCore.cc:1021] errorCode=1 SSL/TLS handshake failure: Invalid certificate chain
[#7d4c1d 10MiB/456MiB(2%) CN:5 SD:0 DL:3.0MiB ETA:2m24s]                                                                                                                                                                                                   
11/28 17:44:03 [NOTICE] CUID#30 - Redirecting to https://webseed.unv.kangz.net/unv-launcher/unvanquished_0.51.1/pkg/res-players_0.51.dpk

11/28 17:44:03 [ERROR] CUID#30 - Download aborted. URI=http://webseed.unv.kangz.net/unv-launcher/unvanquished_0.51.1/pkg/res-players_0.51.dpk
Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://webseed.unv.kangz.net/unv-launcher/unvanquished_0.51.1/pkg/res-players_0.51.dpk
  -> [SocketCore.cc:1021] errorCode=1 SSL/TLS handshake failure: Invalid certificate chain
[#7d4c1d 52MiB/456MiB(11%) CN:16 SD:1 DL:4.2MiB ETA:1m34s]                                                                                                                                                                                                 
11/28 17:44:12 [NOTICE] CUID#23 - Redirecting to https://webseed.unv.kangz.net/unv-launcher/unvanquished_0.51.1/pkg/res-ambient_0.51.dpk

11/28 17:44:13 [ERROR] CUID#23 - Download aborted. URI=http://webseed.unv.kangz.net/unv-launcher/unvanquished_0.51.1/pkg/res-ambient_0.51.dpk
Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://webseed.unv.kangz.net/unv-launcher/unvanquished_0.51.1/pkg/res-ambient_0.51.dpk
  -> [SocketCore.cc:1021] errorCode=1 SSL/TLS handshake failure: Invalid certificate chain
[#7d4c1d 173MiB/456MiB(37%) CN:14 SD:1 DL:4.4MiB ETA:1m4s]                                                                                                                                                                                                 
11/28 17:44:41 [NOTICE] CUID#21 - Redirecting to https://webseed.unv.kangz.net/unv-launcher/unvanquished_0.51.1/pkg/tex-pk02_1.1.dpk

11/28 17:44:42 [ERROR] CUID#21 - Download aborted. URI=http://webseed.unv.kangz.net/unv-launcher/unvanquished_0.51.1/pkg/tex-pk02_1.1.dpk
Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://webseed.unv.kangz.net/unv-launcher/unvanquished_0.51.1/pkg/tex-pk02_1.1.dpk
  -> [SocketCore.cc:1021] errorCode=1 SSL/TLS handshake failure: Invalid certificate chain
[#7d4c1d 255MiB/456MiB(56%) CN:14 SD:4 DL:3.6MiB ETA:55s]                                                                                                                                                                                                  
11/28 17:45:02 [ERROR] CUID#24 - Download aborted. URI=http://webseed.unv.kangz.net/unv-launcher/unvanquished_0.51.1/pkg/map-thunder_1.3.2.dpk
Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://webseed.unv.kangz.net/unv-launcher/unvanquished_0.51.1/pkg/map-thunder_1.3.2.dpk
  -> [SocketCore.cc:1021] errorCode=1 SSL/TLS handshake failure: Invalid certificate chain
[#7d4c1d 272MiB/456MiB(59%) CN:12 SD:4 DL:3.5MiB ETA:52s]                                                                                                                                                                                                  
11/28 17:45:08 [NOTICE] CUID#50 - Redirecting to https://webseed.unv.kangz.net/unv-launcher/unvanquished_0.51.1/pkg/tex-vega_1.4.dpk
[#7d4c1d 275MiB/456MiB(60%) CN:12 SD:4 DL:3.4MiB ETA:52s]                                                                                                                                                                                                  
11/28 17:45:08 [ERROR] CUID#50 - Download aborted. URI=http://webseed.unv.kangz.net/unv-launcher/unvanquished_0.51.1/pkg/tex-vega_1.4.dpk
Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://webseed.unv.kangz.net/unv-launcher/unvanquished_0.51.1/pkg/tex-vega_1.4.dpk
  -> [SocketCore.cc:1021] errorCode=1 SSL/TLS handshake failure: Invalid certificate chain
[#7d4c1d 302MiB/456MiB(66%) CN:12 SD:3 DL:3.6MiB ETA:42s]                                                                                                                                                                                                  
11/28 17:45:15 [NOTICE] CUID#31 - Redirecting to https://webseed.unv.kangz.net/unv-launcher/unvanquished_0.51.1/pkg/map-parpax_2.5.1.dpk

11/28 17:45:15 [ERROR] CUID#31 - Download aborted. URI=http://webseed.unv.kangz.net/unv-launcher/unvanquished_0.51.1/pkg/map-parpax_2.5.1.dpk
Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://webseed.unv.kangz.net/unv-launcher/unvanquished_0.51.1/pkg/map-parpax_2.5.1.dpk
  -> [SocketCore.cc:1021] errorCode=1 SSL/TLS handshake failure: Invalid certificate chain
[#7d4c1d 392MiB/456MiB(85%) CN:16 SD:3 DL:2.7MiB ETA:23s]                                                                                                                                                                                                  
11/28 17:45:43 [NOTICE] CUID#58 - Redirecting to https://webseed.unv.kangz.net/unv-launcher/unvanquished_0.51.1/pkg/unvanquished_0.51.1.dpk

11/28 17:45:43 [ERROR] CUID#58 - Download aborted. URI=http://webseed.unv.kangz.net/unv-launcher/unvanquished_0.51.1/pkg/unvanquished_0.51.1.dpk
Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://webseed.unv.kangz.net/unv-launcher/unvanquished_0.51.1/pkg/unvanquished_0.51.1.dpk
  -> [SocketCore.cc:1021] errorCode=1 SSL/TLS handshake failure: Invalid certificate chain
[#7d4c1d 454MiB/456MiB(99%) CN:11 SD:3 DL:3.5MiB]                                                                                                                                                                                                          
11/28 17:46:03 [NOTICE] Download of selected files was complete.

11/28 17:46:03 [NOTICE] Seeding is over.
[#7d4c1d SEED(0.0) CN:0 SD:0]                                                                                                                                                                                                                              
11/28 17:46:10 [NOTICE] Download complete: /Users/user/Projects/Unvanquished/build/pkg/.cache/unvanquished_0.51.1

11/28 17:46:10 [NOTICE] Your share ratio was 0.0, uploaded/downloaded=0B/456MiB
                                                                                                                                                                                                                                                           
Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
7d4c1d|OK  |   3.6MiB/s|/Users/user/Projects/Unvanquished/build/pkg/.cache/unvanquished_0.51.1/pkg/map-antares_1.dpk (30more)

Status Legend:
(OK):download completed.
Downloaded.
Verifying files…
Errors found during verification. Re-downloading is recommended.
Cleaning-up cache…
Finished.


```

**Comment by slipher** [comment]
The crash is the GLEW issue, #1228.

**Comment by necessarily-equal** [comment]
Hi, thanks for this issue. Has it been solved since? Anything left we can do?
