### ISSUE TITLE
Segfault in bot BT

### ISSUE THREAD

**Issue by necessarily-equal** [Unvanquished/Unvanquished#2279]
I've seen this segfault. I don't know where it comes from. https://paste.gnugen.ch/paste/uu5L.

<del>I've only ever seen it once so it shouldn't be too important.</del> This is 100% reproducible now with default BT.

**Comment by DolceTriade** [comment]
Memory leak? `malloc` shouldn't fail otherwise?

**Comment by necessarily-equal** [comment]
`malloc_printerr` says "corrupted size vs. prev_size in fastbins". I don't think it's an out-of-memory error or it would have returned nullptr instead.

**Comment by necessarily-equal** [comment]
From the calloc documentation:

> This function returns a pointer to the allocated memory, or NULL if the request fails.

This looks more serious than an out-of-memory

**Comment by necessarily-equal** [comment]
I've seen it again. What's interesting is that it seems to happen with the "use_medikit" BT.

```gdb
Starting DNS resolver thread              
][New Thread 0x7ffff272b640 (LWP 34)]
Warn: Hitch: 1643 msec frame time         
]corrupted size vs. prev_size in fastbins                                                                                                                                                                         
Thread 4 "daemonded" received signal SIGABRT, Aborted.

Thread 4 (Thread 0x7ffff32dc640 (LWP 33) "daemonded"):
#0  0x00007ffff7a56c1f in __pthread_kill_implementation () from /nix/store/f6kvkdzp6qfjm6h94d0jgfvm4r06xcaq-glibc-2.34-210/lib/libc.so.6
#1  0x00007ffff7a0c042 in raise () from /nix/store/f6kvkdzp6qfjm6h94d0jgfvm4r06xcaq-glibc-2.34-210/lib/libc.so.6
#2  0x00007ffff79f749c in abort () from /nix/store/f6kvkdzp6qfjm6h94d0jgfvm4r06xcaq-glibc-2.34-210/lib/libc.so.6
#3  0x00007ffff7a4b3f8 in __libc_message () from /nix/store/f6kvkdzp6qfjm6h94d0jgfvm4r06xcaq-glibc-2.34-210/lib/libc.so.6
#4  0x00007ffff7a6029a in malloc_printerr () from /nix/store/f6kvkdzp6qfjm6h94d0jgfvm4r06xcaq-glibc-2.34-210/lib/libc.so.6
#5  0x00007ffff7a60934 in malloc_consolidate () from /nix/store/f6kvkdzp6qfjm6h94d0jgfvm4r06xcaq-glibc-2.34-210/lib/libc.so.6
#6  0x00007ffff7a62a9c in _int_malloc () from /nix/store/f6kvkdzp6qfjm6h94d0jgfvm4r06xcaq-glibc-2.34-210/lib/libc.so.6
#7  0x00007ffff7a64cc8 in calloc () from /nix/store/f6kvkdzp6qfjm6h94d0jgfvm4r06xcaq-glibc-2.34-210/lib/libc.so.6
#8  0x00007ffff4d1b094 in BG_Alloc (size=2209) at /build/source/src/shared/bg_alloc.cpp:32
#9  Parse_LoadScriptMemory(char const*, int, char const*) [clone .constprop.0] (ptr=0x7ffff53695a5 <va(char const*, ...)::string+12197> "UP_LIGHTARMOUR 1", length=16, name=0x7ffff4d57dab "*extern") at /build/source/src/shared/parse.cpp:1201
#10 0x00007ffff4ce82f3 in Parse_DefineFromString (string=<optimized out>) at /build/source/src/shared/parse.cpp:3887
#11 0x00007ffff4d3dacd in Parse_AddGlobalDefine(char const*) [clone .isra.0] (string=<optimized out>) at /build/source/src/shared/parse.cpp:3954
#12 0x00007ffff4c6f91d in ReadBehaviorTree (name=name@entry=0x7fffec13e230 "use_medkit", list=list@entry=0x7ffff532d380 <treeList>) at /build/source/src/sgame/sg_bot_parse.cpp:1288
#13 0x00007ffff4c70893 in ReadBehaviorTree (list=0x7ffff532d380 <treeList>, name=0x7fffec13e230 "use_medkit") at /build/source/src/sgame/sg_bot_parse.cpp:1014
#14 ReadBehaviorTreeInclude (tokenlist=0x7ffff32dad10) at /build/source/src/sgame/sg_bot_parse.cpp:1178
#15 ReadNode (tokenlist=tokenlist@entry=0x7ffff32dada0) at /build/source/src/sgame/sg_bot_parse.cpp:1245
#16 0x00007ffff4c70d5a in ReadNodeList (tokenlist=tokenlist@entry=0x7ffff32dae10) at /build/source/src/sgame/sg_bot_parse.cpp:1123
#17 0x00007ffff4c70373 in ReadSelector (tokenlist=0x7ffff32dae00) at /build/source/src/sgame/sg_bot_parse.cpp:1072
#18 ReadNode (tokenlist=tokenlist@entry=0x7ffff32dae98) at /build/source/src/sgame/sg_bot_parse.cpp:1217
#19 0x00007ffff4c70158 in ReadBehaviorTree (name=name@entry=0x7fffec143480 "default_humans", list=list@entry=0x7ffff532d380 <treeList>) at /build/source/src/sgame/sg_bot_parse.cpp:1395
#20 0x00007ffff4c70893 in ReadBehaviorTree (list=0x7ffff532d380 <treeList>, name=0x7fffec143480 "default_humans") at /build/source/src/sgame/sg_bot_parse.cpp:1014
#21 ReadBehaviorTreeInclude (tokenlist=0x7ffff32daf50) at /build/source/src/sgame/sg_bot_parse.cpp:1178
#22 ReadNode (tokenlist=tokenlist@entry=0x7ffff32db000) at /build/source/src/sgame/sg_bot_parse.cpp:1245
#23 0x00007ffff4c705a0 in ReadConditionNode (tokenlist=0x7ffff32daff0) at /build/source/src/sgame/sg_bot_parse.cpp:806
#24 ReadNode (tokenlist=tokenlist@entry=0x7ffff32db080) at /build/source/src/sgame/sg_bot_parse.cpp:1237
#25 0x00007ffff4c70d5a in ReadNodeList (tokenlist=tokenlist@entry=0x7ffff32db0f0) at /build/source/src/sgame/sg_bot_parse.cpp:1123
#26 0x00007ffff4c70373 in ReadSelector (tokenlist=0x7ffff32db0e0) at /build/source/src/sgame/sg_bot_parse.cpp:1072
#27 ReadNode (tokenlist=tokenlist@entry=0x7ffff32db178) at /build/source/src/sgame/sg_bot_parse.cpp:1217
#28 0x00007ffff4c70158 in ReadBehaviorTree (name=name@entry=0x7ffff4d4c1a0 <BOT_DEFAULT_BEHAVIOR> "default", list=list@entry=0x7ffff532d380 <treeList>) at /build/source/src/sgame/sg_bot_parse.cpp:1395
#29 0x00007ffff4c75413 in ReadBehaviorTree (list=0x7ffff532d380 <treeList>, name=0x7ffff4d4c1a0 <BOT_DEFAULT_BEHAVIOR> "default") at /build/source/src/sgame/sg_bot.cpp:237
#30 G_BotSetBehavior (botMind=0x7ffff5319b48 <_ZL9g_botMind.lto_priv.0+1224>, behavior=...) at /build/source/src/sgame/sg_bot.cpp:223
#31 0x00007ffff4d1aed7 in G_BotSetDefaults(int, team_t, int, Str::BasicStringRef<char>) [clone .constprop.0] (clientNum=clientNum@entry=1, team=team@entry=TEAM_ALIENS, behavior=..., skill=<optimized out>) at /build/source/src/sgame/sg_bot.cpp:248
#32 0x00007ffff4c74aa2 in G_BotAdd (name=<optimized out>, team=TEAM_ALIENS, skill=0, behavior=0x7ffff4d4c1a0 <BOT_DEFAULT_BEHAVIOR> "default", filler=<optimized out>) at /build/source/src/sgame/sg_bot.cpp:294
```

**Comment by necessarily-equal** [comment]
I've seen it again

```gdb
Thread 4 (Thread 0x7ffff306c640 (LWP 33) "daemonded"):                                                                                                                  
#0  0x00007ffff7a56c1f in __pthread_kill_implementation () from /nix/store/f6kvkdzp6qfjm6h94d0jgfvm4r06xcaq-glibc-2.34-210/lib/libc.so.6                                
#1  0x00007ffff7a0c042 in raise () from /nix/store/f6kvkdzp6qfjm6h94d0jgfvm4r06xcaq-glibc-2.34-210/lib/libc.so.6                                                        
#2  0x00007ffff79f749c in abort () from /nix/store/f6kvkdzp6qfjm6h94d0jgfvm4r06xcaq-glibc-2.34-210/lib/libc.so.6                                                        
#3  0x00007ffff7a4b3f8 in __libc_message () from /nix/store/f6kvkdzp6qfjm6h94d0jgfvm4r06xcaq-glibc-2.34-210/lib/libc.so.6                                               
#4  0x00007ffff7a6029a in malloc_printerr () from /nix/store/f6kvkdzp6qfjm6h94d0jgfvm4r06xcaq-glibc-2.34-210/lib/libc.so.6                                              
#5  0x00007ffff7a60934 in malloc_consolidate () from /nix/store/f6kvkdzp6qfjm6h94d0jgfvm4r06xcaq-glibc-2.34-210/lib/libc.so.6                                           
#6  0x00007ffff7a62a9c in _int_malloc () from /nix/store/f6kvkdzp6qfjm6h94d0jgfvm4r06xcaq-glibc-2.34-210/lib/libc.so.6                                                  
#7  0x00007ffff7a64cc8 in calloc () from /nix/store/f6kvkdzp6qfjm6h94d0jgfvm4r06xcaq-glibc-2.34-210/lib/libc.so.6                                                       
#8  0x00007ffff4a70d34 in BG_Alloc (size=2508) at /build/source/src/shared/bg_alloc.cpp:32                                                                              
#9  Parse_LoadScriptFile (filename=filename@entry=0x7ffff306acc0 "bots/use_medkit.bt", openFunc=openFunc@entry=0x7ffff4a4f0b0 <G_FOpenGameOrPakPath(Str::BasicStringRef<char>, int&)>) at /build/source/src/shared/parse.cpp:1163
#10 0x00007ffff4a78aec in Parse_LoadSourceFile (openFunc=0x7ffff4a4f0b0, G_FOpenGameOrPakPath(Str::BasicStringRef<char>, int&)>, filename=0x7ffff306acc0 "bots/use_medkit.bt") at /build/source/src/shared/parse.cpp:4088
#11 Parse_LoadSourceHandle (filename=0x7ffff306acc0 "bots/use_medkit.bt", openFunc=0x7ffff4a4f0b0 <G_FOpenGameOrPakPath(Str::BasicStringRef<char>, int&)>) at /build/source/src/shared/parse.cpp:4193                                                                                                                                           
#12 0x00007ffff4a0a8cb in ReadBehaviorTree (name=0x7fffec12f940 "use_medkit", list=0x7ffff50bca90 <treeList>) at /build/source/src/sgame/sg_bot_parse.cpp:1380
#13 0x00007ffff4a04da3 in ReadBehaviorTree (list=0x7ffff50bca90 <treeList>, name=0x7fffec12f940 "use_medkit") at /build/source/src/sgame/sg_bot_parse.cpp:1007          
#14 ReadBehaviorTreeInclude (tokenlist=0x7ffff306ad70) at /build/source/src/sgame/sg_bot_parse.cpp:1171                                                                 
#15 ReadNode (tokenlist=tokenlist@entry=0x7ffff306ae00) at /build/source/src/sgame/sg_bot_parse.cpp:1238                                                                
#16 0x00007ffff4a0526a in ReadNodeList (tokenlist=tokenlist@entry=0x7ffff306ae70) at /build/source/src/sgamesg_bot_parse.cpp:1116                                      
#17 0x00007ffff4a04883 in ReadSelector (tokenlist=0x7ffff306ae60) at /build/source/src/sgame/sg_bot_parse.cpp:1065                                                      
#18 ReadNode (tokenlist=0x7ffff306aef8) at /build/source/src/sgame/sg_bot_parse.cpp:1210                                                                                
#19 0x00007ffff4a0a978 in ReadBehaviorTree (name=<optimized out>, list=0x7ffff50bca90 <treeList>) at /build/source/src/sgame/sg_bot_parse.cpp:1401                      
#20 0x00007ffff4a04da3 in ReadBehaviorTree (list=0x7ffff50bca90 <treeList>, name=0x7fffec142d30 "default_humans") at /build/source/src/sgame/sg_bot_parse.cpp:1007
#21 ReadBehaviorTreeInclude (tokenlist=0x7ffff306afb0) at /build/source/src/sgame/sg_bot_parse.cpp:1171
#22 ReadNode (tokenlist=tokenlist@entry=0x7ffff306b060) at /build/source/src/sgame/sg_bot_parse.cpp:1238
#23 0x00007ffff4a04ab0 in ReadConditionNode (tokenlist=0x7ffff306b050) at /build/source/src/sgame/sg_bot_parse.cpp:799
#24 ReadNode (tokenlist=tokenlist@entry=0x7ffff306b0e0) at /build/source/src/sgame/sg_bot_parse.cpp:1230
#25 0x00007ffff4a0526a in ReadNodeList (tokenlist=tokenlist@entry=0x7ffff306b150) at /build/source/src/sgame/sg_bot_parse.cpp:1116
#26 0x00007ffff4a04883 in ReadSelector (tokenlist=0x7ffff306b140) at /build/source/src/sgame/sg_bot_parse.cpp:1065
#27 ReadNode (tokenlist=0x7ffff306b1d8) at /build/source/src/sgame/sg_bot_parse.cpp:1210
#28 0x00007ffff4a0a978 in ReadBehaviorTree (name=<optimized out>, list=0x7ffff50bca90 <treeList>) at /build/source/src/sgame/sg_bot_parse.cpp:1401
#29 0x00007ffff4a05c43 in ReadBehaviorTree (list=0x7ffff50bca90 <treeList>, name=0x7ffff4adcc40 <BOT_DEFAULT_BEHAVIOR> "default") at /build/source/src/sgame/sg_bot.cpp:239
```

**Comment by necessarily-equal** [comment]
and again
```C++
]corrupted size vs. prev_size in fastbins                                                                                                                               
                                                                                                                                                                        
Thread 4 "daemonded" received signal SIGABRT, Aborted.   

Thread 4 (Thread 0x7ffff306c640 (LWP 33) "daemonded"):                                                                                                                  
#0  0x00007ffff7a56c1f in __pthread_kill_implementation () from /nix/store/f6kvkdzp6qfjm6h94d0jgfvm4r06xcaq-glibc-2.34-210/lib/libc.so.6                                
#1  0x00007ffff7a0c042 in raise () from /nix/store/f6kvkdzp6qfjm6h94d0jgfvm4r06xcaq-glibc-2.34-210/lib/libc.so.6                                                        
#2  0x00007ffff79f749c in abort () from /nix/store/f6kvkdzp6qfjm6h94d0jgfvm4r06xcaq-glibc-2.34-210/lib/libc.so.6                                                        
#3  0x00007ffff7a4b3f8 in __libc_message () from /nix/store/f6kvkdzp6qfjm6h94d0jgfvm4r06xcaq-glibc-2.34-210/lib/libc.so.6                                               
#4  0x00007ffff7a6029a in malloc_printerr () from /nix/store/f6kvkdzp6qfjm6h94d0jgfvm4r06xcaq-glibc-2.34-210/lib/libc.so.6
#5  0x00007ffff7a60934 in malloc_consolidate () from /nix/store/f6kvkdzp6qfjm6h94d0jgfvm4r06xcaq-glibc-2.34-210/lib/libc.so.6
#6  0x00007ffff7a62a9c in _int_malloc () from /nix/store/f6kvkdzp6qfjm6h94d0jgfvm4r06xcaq-glibc-2.34-210/lib/libc.so.6
#7  0x00007ffff7a64cc8 in calloc () from /nix/store/f6kvkdzp6qfjm6h94d0jgfvm4r06xcaq-glibc-2.34-210/lib/libc.so.6
#8  0x00007ffff4a70d34 in BG_Alloc (size=2508) at /build/source/src/shared/bg_alloc.cpp:32
#9  Parse_LoadScriptFile (filename=filename@entry=0x7ffff306acc0 "bots/use_medkit.bt", openFunc=openFunc@entry=0x7ffff4a4f0b0 <G_FOpenGameOrPakPath(Str::BasicStringRef<char>, int&)>) at /build/source/src/shared/parse.cpp:1163                           
#10 0x00007ffff4a78aec in Parse_LoadSourceFile (openFunc=0x7ffff4a4f0b0 <G_FOpenGameOrPakPath(Str::BasicStringRef<char>, int&)>, filename=0x7ffff306acc0 "bots/use_medki
t.bt") at /build/source/src/shared/parse.cpp:4088                                   
#11 Parse_LoadSourceHandle (filename=0x7ffff306acc0 "bots/use_medkit.bt", openFunc=0x7ffff4a4f0b0 <G_FOpenGameOrPakPath(Str::BasicStringRef<char>, int&)>) at /build/source/src/shared/parse.cpp:4193             
#12 0x00007ffff4a0a8cb in ReadBehaviorTree (name=0x7fffec12f940 "use_medkit", list=0x7ffff50bca90 <treeList>) at /build/source/src/sgame/sg_bot_parse.cpp:1380
#13 0x00007ffff4a04da3 in ReadBehaviorTree (list=0x7ffff50bca90 <treeList>, name=0x7fffec12f940 "use_medkit") at /build/source/src/sgame/sg_bot_parse.cpp:1007
#14 ReadBehaviorTreeInclude (tokenlist=0x7ffff306ad70) at /build/source/src/sgame/sg_bot_parse.cpp:1171
#15 ReadNode (tokenlist=tokenlist@entry=0x7ffff306ae00) at /build/source/src/sgame/sg_bot_parse.cpp:1238
#16 0x00007ffff4a0526a in ReadNodeList (tokenlist=tokenlist@entry=0x7ffff306ae70) at /build/source/src/sgame/sg_bot_parse.cpp:1116
#17 0x00007ffff4a04883 in ReadSelector (tokenlist=0x7ffff306ae60) at /build/source/src/sgame/sg_bot_parse.cpp:1065
#18 ReadNode (tokenlist=0x7ffff306aef8) at /build/source/src/sgame/sg_bot_parse.cpp:1210
#19 0x00007ffff4a0a978 in ReadBehaviorTree (name=<optimized out>, list=0x7ffff50bca90 <treeList>) at /build/source/src/sgame/sg_bot_parse.cpp:1401
#20 0x00007ffff4a04da3 in ReadBehaviorTree (list=0x7ffff50bca90 <treeList>, name=0x7fffec142d30 "default_humans") at /build/source/src/sgame/sg_bot_parse.cpp:1007
#21 ReadBehaviorTreeInclude (tokenlist=0x7ffff306afb0) at /build/source/src/sgame/sg_bot_parse.cpp:1171
#22 ReadNode (tokenlist=tokenlist@entry=0x7ffff306b060) at /build/source/src/sgame/sg_bot_parse.cpp:1238
#23 0x00007ffff4a04ab0 in ReadConditionNode (tokenlist=0x7ffff306b050) at /build/source/src/sgame/sg_bot_parse.cpp:799
#24 ReadNode (tokenlist=tokenlist@entry=0x7ffff306b0e0) at /build/source/src/sgame/sg_bot_parse.cpp:1230
#25 0x00007ffff4a0526a in ReadNodeList (tokenlist=tokenlist@entry=0x7ffff306b150) at /build/source/src/sgame/sg_bot_parse.cpp:1116
#26 0x00007ffff4a04883 in ReadSelector (tokenlist=0x7ffff306b140) at /build/source/src/sgame/sg_bot_parse.cpp:1065
#27 ReadNode (tokenlist=0x7ffff306b1d8) at /build/source/src/sgame/sg_bot_parse.cpp:1210
