### ISSUE TITLE
Server crashes

### ISSUE THREAD

**Issue by sweet235** [Unvanquished/Unvanquished#2692]
For reasons I do not yet know, current master leads to frequent server crashes. I do not good and bad commits, these are: good e5d57bc2e, bad 3145e8e78.

**Comment by cu-kai** [comment]
My observations so far are that this is bot related, specifically to do with when bots are joining/leaving the server.

I have observed the following crashes:
Uncreation PvE on @sweet235's server, when @sweet235 joined the alien team and a bot was punted from the team.


& on Bunker based on commit dfed78440b5a6252a6e853d1a340eb28c015f82c + Sudden Death (@ this commit: https://github.com/cu-kai/Unvanquished/tree/1dd90ebc401516e45f26d0b0a9854e056e9c9fcc):
* running `bot del all` on zittrig-arena
* running `bot del all` on ptcs1

I cannot reliably reproduce this.

**Comment by sweet235** [comment]
I should add that bisecting is not easy, as it might very well take over an hour for a crash to happen.

**Comment by sweet235** [comment]
> might very well take over an hour

It might be over 12 hours.

**Comment by cu-kai** [comment]
I have conducted further testing and can fairly reliably reproduce this crash on the map `dretchstorm` on Bunker server at the commit mentioned in my previous comment. The crash seems to be caused by bots being removed while under attack by a machinegun turret.

To reproduce: load the map `dretchstorm`,
`/bot fill 20 a`

When they start being attacked by the turrets at the starting base,
`/bot del all`

The server should crash.

I have obtained the following stacktrace:
```
AdminExec: ok: 0 "d(ノ-_-)bノミ┻━┻" "d(ノ-_-)bノミ┻━┻" [98] (-snip-): bot
]
Thread 6 "daemonded" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff15fe6c0 (LWP 946563)]
TurretComponent::TargetValid (this=0x7fffec06ac00, target=..., newTarget=newTarget@entry=false)
    at GIT/unvanquished/src/sgame/components/TurretComponent.cpp:198
198             if (!target.Get<ClientComponent>() ||
(gdb) bt
#0  TurretComponent::TargetValid (this=0x7fffec06ac00, target=..., newTarget=newTarget@entry=false)
    at GIT/unvanquished/src/sgame/components/TurretComponent.cpp:198
#1  0x00007ffff46df12a in TurretComponent::TargetValid (this=<optimized out>)
    at GIT/unvanquished/src/sgame/components/TurretComponent.cpp:56
#2  0x00007ffff46d51bc in MGTurretComponent::Think (this=0x7fffec06ac40, timeDelta=25)
    at GIT/unvanquished/src/sgame/components/MGTurretComponent.cpp:68
#3  0x00007ffff46d5354 in operator() (i=<optimized out>, __closure=<optimized out>)
    at GIT/unvanquished/src/sgame/components/MGTurretComponent.cpp:17
#4  std::__invoke_impl<void, MGTurretComponent::MGTurretComponent(Entity&, HumanBuildableComponent&, TurretComponent&)::<lambda(int)>&, int> (__f=...) at /usr/include/c++/12.2.1/bits/invoke.h:61
#5  std::__invoke_r<void, MGTurretComponent::MGTurretComponent(Entity&, HumanBuildableComponent&, TurretComponent&)::<lambda(int)>&, int> (__fn=...) at /usr/include/c++/12.2.1/bits/invoke.h:154
#6  std::_Function_handler<void(int), MGTurretComponent::MGTurretComponent(Entity&, HumanBuildableComponent&, TurretComponent&)::<lambda(int)> >::_M_invoke(const std::_Any_data &, int &&) (__functor=..., __args#0=<optimized out>)
    at /usr/include/c++/12.2.1/bits/std_function.h:290
#7  0x00007ffff466350b in std::function<void (int)>::operator()(int) const (this=this@entry=0x7fffec3484d8,
    __args#0=<optimized out>, __args#0@entry=25) at /usr/include/c++/12.2.1/bits/std_function.h:591
#8  0x00007ffff46dd0ae in ThinkingComponent::Think (this=0x7fffec06ab30)
    at GIT/unvanquished/src/sgame/components/ThinkingComponent.cpp:65
#9  0x00007ffff468c496 in G_RunThink (ent=ent@entry=0x7fffe892de40)
    at GIT/unvanquished/src/sgame/sg_main.cpp:2235
#10 0x00007ffff46a085f in G_Physics (ent=ent@entry=0x7fffe892de40)
    at GIT/unvanquished/src/sgame/sg_physics.cpp:122
#11 0x00007ffff468e73f in G_RunFrame (levelTime=<optimized out>)
    at GIT/unvanquished/src/sgame/sg_main.cpp:2447
#12 0x00007ffff464b839 in operator() (levelTime=<optimized out>, __closure=0x7ffff15fdd27)
    at GIT/unvanquished/src/sgame/sg_api.cpp:132
#13 Util::apply_impl<VM::VMHandleSyscall(uint32_t, Util::Reader)::<lambda(int)>, std::tuple<int&&>, 0>(struct {...} &&, std::tuple<int&&> &&, Util::seq<0>) (func=..., tuple=...) at GIT/unvanquished/daemon/src/common/Util.h:125
#14 0x00007ffff464b847 in Util::apply<VM::VMHandleSyscall(uint32_t, Util::Reader)::<lambda(int)>, std::tuple<int&&> >(struct {...} &&, std::tuple<int&&> &&) (func=..., tuple=...)
    at GIT/unvanquished/daemon/src/common/Util.h:130
#15 0x00007ffff464c852 in IPC::detail::HandleMsg<VM::VMHandleSyscall(uint32_t, Util::Reader)::<lambda(int)>, IPC::Message<IPC::Id<0, 9>, int>, IPC::Reply<> >(IPC::Channel &, IPC::SyncMessage<IPC::Message<IPC::Id<0, 9>, int>, IPC::Reply<> >, Util::Reader, struct {...} &&) (channel=..., reader=..., func=...)
    at GIT/unvanquished/daemon/src/common/IPC/Channel.h:217
#16 0x00007ffff464c93c in IPC::HandleMsg<IPC::SyncMessage<IPC::Message<IPC::Id<0, 9>, int> >, VM::VMHandleSyscall(uint32_t, Util::Reader)::<lambda(int)> >(IPC::Channel &, Util::Reader, struct {...} &&) (channel=..., reader=..., func=...)
    at GIT/unvanquished/daemon/src/common/IPC/Channel.h:241
#17 0x00007ffff464ce1e in VM::VMHandleSyscall (id=id@entry=9, reader=...)
    at GIT/unvanquished/src/sgame/sg_api.cpp:131
#18 0x00007ffff4727db1 in CommonInit (rootSocket=<optimized out>)
    at GIT/unvanquished/daemon/src/shared/VMMain.cpp:66
#19 0x00007ffff4727ecc in vmMain (rootSocket=<optimized out>)
    at GIT/unvanquished/daemon/src/shared/VMMain.cpp:104
#20 0x000055555562deff in std::thread::_State_impl<std::thread::_Invoker<std::tuple<VM::CreateInProcessNativeVM(std::pair<IPC::Socket, IPC::Socket>, Str::BasicStringRef<char>, VM::VMBase::InProcessInfo&)::{lambda()#1}> > >::_M_run() ()
#21 0x00007ffff7ad72c3 in std::execute_native_thread_routine (__p=0x555555fc7520)
    at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/thread.cc:82
#22 0x00007ffff789ebb5 in ?? () from /usr/lib/libc.so.6
#23 0x00007ffff7920d90 in ?? () from /usr/lib/libc.so.6
```

**Comment by slipher** [comment]
This should hopefully fix it:

```patch
diff --git a/src/sgame/components/TurretComponent.h b/src/sgame/components/TurretComponent.h
index 11844c56a..91a482eb1 100644
--- a/src/sgame/components/TurretComponent.h
+++ b/src/sgame/components/TurretComponent.h
@@ -114,7 +114,7 @@ class TurretComponent: public TurretComponentBase {
                glm::vec3 RelativeAnglesToDirection(const glm::vec3 relativeAngles) const;

                /** An entity target that the turret can track. */
-               gentity_t* target;
+               GentityRef target;

                /** The attack range of the turret, used for checking whether a target can be hit. */
                float range;
```

**Comment by cu-kai** [comment]
Yes that seems to fix it, thanks.

**Comment by sweet235** [comment]
Do we really know what we are doing?
