### ISSUE TITLE
Segfault in `trap_R_AddPolysToScene` when firing SMG on dll game compiled with AOCC on Linux

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#2878]
I don't know if that's a compiler bug or not, I only reproduce this with the [AMD AOCC compiler](https://www.amd.com/fr/developer/aocc.html) on Ubuntu.

How I reproduce: I open plat23 map, spawn as human, fire the SMG until it crashes.

I reproduce the bug on `Release` and `RelWithDebInfo` builds, not on `Debug` build.

This is a bug I noticed months ago on AOCC 4.0, I confirm I can still reproduce it on AOCC 4.1.

Maybe it's a compiler bug as I only reproduce it on AOCC, but maybe it reveals a real bug.

Here is a stacktrace:

```gdb
Thread 20 "daemon" received signal SIGSEGV, Segmentation fault.

0x00007fff78fd4794 in std::__fill_a1<polyVert_t*, polyVert_t> (__first=0x7fff8b922ff0, __last=<optimized out>, __value=...) at /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_algobase.h:919
919		*__first = __value;

Thread 20 (Thread 0x7fffa10d36c0 (LWP 273149) "daemon"):
#0  0x00007fff78fd4794 in std::__fill_a1<polyVert_t*, polyVert_t> (__first=0x7fff8b922ff0, __last=<optimized out>, __value=...) at /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_algobase.h:919
#1  std::__fill_a<polyVert_t*, polyVert_t> (__first=<optimized out>, __last=<optimized out>, __value=...) at /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_algobase.h:977
#2  std::__fill_n_a<polyVert_t*, unsigned long, polyVert_t> (__first=<optimized out>, __n=18446744073709551615, __value=...) at /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_algobase.h:1128
#3  std::fill_n<polyVert_t*, unsigned long, polyVert_t> (__first=<optimized out>, __n=18446744073709551615, __value=...) at /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_algobase.h:1157
#4  std::__uninitialized_default_n_1<true>::__uninit_default_n<polyVert_t*, unsigned long> (__first=<optimized out>, __n=0) at /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_uninitialized.h:668
#5  std::__uninitialized_default_n<polyVert_t*, unsigned long> (__first=0x7fff8a9d6280, __n=0) at /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_uninitialized.h:710
#6  std::__uninitialized_default_n_a<polyVert_t*, unsigned long, polyVert_t> (__first=0x7fff8a9d6280, __n=0) at /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_uninitialized.h:779
#7  std::vector<polyVert_t, std::allocator<polyVert_t> >::_M_default_initialize (this=0x7fffa10c59b8, __n=0) at /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_vector.h:1715
#8  std::vector<polyVert_t, std::allocator<polyVert_t> >::vector (this=0x7fffa10c59b8, __n=0, __a=...) at /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_vector.h:555
#9  trap_R_AddPolysToScene (hShader=<optimized out>, numVerts=numVerts@entry=4, verts=verts@entry=0x7fffa10c5c80, numPolys=<optimized out>) at Unvanquished/daemon/src/shared/client/cg_api.cpp:329
#10 0x00007fff78f7614a in CG_RenderBeam (tb=0x7fff7de8c8b0 <trailBeams>) at Unvanquished/src/cgame/cg_trails.cpp:305
#11 CG_AddTrails () at Unvanquished/src/cgame/cg_trails.cpp:1612
#12 0x00007fff78f7b387 in CG_DrawActiveFrame (serverTime=<optimized out>, demoPlayback=<optimized out>) at Unvanquished/src/cgame/cg_view.cpp:1936
#13 0x00007fff78f16cdc in VM::VMHandleSyscall(unsigned int, Util::Reader)::$_5::operator()(int, bool) const (serverTime=16, this=<optimized out>, demoPlayback=<optimized out>) at Unvanquished/src/cgame/cg_api.cpp:89
#14 Util::apply_impl<VM::VMHandleSyscall(unsigned int, Util::Reader)::$_5, std::tuple<int&&, bool&&>, 0ul, 1ul>(VM::VMHandleSyscall(unsigned int, Util::Reader)::$_5&&, std::tuple<int&&, bool&&>&&, Util::seq<0ul, 1ul>) (func=..., tuple=...) at Unvanquished/daemon/src/common/Util.h:125
#15 Util::apply<VM::VMHandleSyscall(unsigned int, Util::Reader)::$_5, std::tuple<int&&, bool&&> >(VM::VMHandleSyscall(unsigned int, Util::Reader)::$_5&&, std::tuple<int&&, bool&&>&&) (func=..., tuple=...) at Unvanquished/daemon/src/common/Util.h:130
#16 IPC::detail::HandleMsg<VM::VMHandleSyscall(unsigned int, Util::Reader)::$_5, IPC::Message<IPC::Id<(unsigned short)0, (unsigned short)3>, int, bool>, IPC::Reply<> >(IPC::Channel&, IPC::SyncMessage<IPC::Message<IPC::Id<(unsigned short)0, (unsigned short)3>, int, bool>, IPC::Reply<> >, Util::Reader, VM::VMHandleSyscall(unsigned int, Util::Reader)::$_5&&) (reader=..., channel=..., func=...) at Unvanquished/daemon/src/common/IPC/Channel.h:217
#17 IPC::HandleMsg<IPC::SyncMessage<IPC::Message<IPC::Id<(unsigned short)0, (unsigned short)3>, int, bool>, IPC::Reply<> >, VM::VMHandleSyscall(unsigned int, Util::Reader)::$_5>(IPC::Channel&, Util::Reader, VM::VMHandleSyscall(unsigned int, Util::Reader)::$_5&&) (reader=..., channel=..., func=...) at Unvanquished/daemon/src/common/IPC/Channel.h:241
#18 VM::VMHandleSyscall (id=<optimized out>, reader=...) at Unvanquished/src/cgame/cg_api.cpp:88
#19 0x00007fff79002906 in CommonInit (rootSocket=<optimized out>) at Unvanquished/daemon/src/shared/VMMain.cpp:66
#20 vmMain (rootSocket=<optimized out>) at Unvanquished/daemon/src/shared/VMMain.cpp:104
#21 0x00005555557f0dce in VM::CreateInProcessNativeVM(std::pair<IPC::Socket, IPC::Socket>, Str::BasicStringRef<char>, VM::VMBase::InProcessInfo&)::$_0::operator()() const (this=0x555558001148) at Unvanquished/daemon/src/engine/framework/VirtualMachine.cpp:364
#22 std::__invoke_impl<void, VM::CreateInProcessNativeVM(std::pair<IPC::Socket, IPC::Socket>, Str::BasicStringRef<char>, VM::VMBase::InProcessInfo&)::$_0>(std::__invoke_other, VM::CreateInProcessNativeVM(std::pair<IPC::Socket, IPC::Socket>, Str::BasicStringRef<char>, VM::VMBase::InProcessInfo&)::$_0&&) (__f=...) at /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/invoke.h:61
#23 std::__invoke<VM::CreateInProcessNativeVM(std::pair<IPC::Socket, IPC::Socket>, Str::BasicStringRef<char>, VM::VMBase::InProcessInfo&)::$_0>(VM::CreateInProcessNativeVM(std::pair<IPC::Socket, IPC::Socket>, Str::BasicStringRef<char>, VM::VMBase::InProcessInfo&)::$_0&&) (__fn=...) at /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/invoke.h:96
#24 std::thread::_Invoker<std::tuple<VM::CreateInProcessNativeVM(std::pair<IPC::Socket, IPC::Socket>, Str::BasicStringRef<char>, VM::VMBase::InProcessInfo&)::$_0> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x555558001148) at /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/std_thread.h:292
#25 std::thread::_Invoker<std::tuple<VM::CreateInProcessNativeVM(std::pair<IPC::Socket, IPC::Socket>, Str::BasicStringRef<char>, VM::VMBase::InProcessInfo&)::$_0> >::operator()() (this=0x555558001148) at /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/std_thread.h:299
#26 std::thread::_State_impl<std::thread::_Invoker<std::tuple<VM::CreateInProcessNativeVM(std::pair<IPC::Socket, IPC::Socket>, Str::BasicStringRef<char>, VM::VMBase::InProcessInfo&)::$_0> > >::_M_run() (this=0x555558001140) at /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/std_thread.h:244
#27 0x00007ffff72e6333 in std::execute_native_thread_routine (__p=0x555558001140) at ../../../../../src/libstdc++-v3/src/c++11/thread.cc:104
#28 0x00007ffff6e97ada in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:444
#29 0x00007ffff6f2847c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

Thread 19 (Thread 0x7fffac9276c0 (LWP 273147) "daemon"):
#0  0x00007ffff6f2a637 in __recvmsg_syscall (flags=0, msg=0x7fffac9267d8, fd=49) at ../sysdeps/unix/sysv/linux/recvmsg.c:27
#1  __libc_recvmsg (fd=49, msg=0x7fffac9267d8, flags=0) at ../sysdeps/unix/sysv/linux/recvmsg.c:41
#2  0x00007fff8e1da848 in NaClReceiveDatagram (handle=49, message=0x7fffac9268b0, flags=<optimized out>) at Unvanquished/daemon/libs/nacl/native_client/src/shared/imc/linux/nacl_imc.cc:168
#3  0x00007fff8e1997bd in IPC::InternalRecvMsg (handle=49, reader=...) at Unvanquished/daemon/src/common/IPC/Primitives.cpp:380
#4  0x00007fff8e199b2b in IPC::Socket::RecvMsg (this=0x7fff8e2f0718 <VM::rootChannel>) at Unvanquished/daemon/src/common/IPC/Primitives.cpp:470
#5  0x00007fff8e18653b in IPC::Channel::RecvMsg (this=0x7fff8e2f0718 <VM::rootChannel>) at Unvanquished/daemon/src/common/IPC/Channel.h:111
#6  CommonInit (rootSocket=<optimized out>) at Unvanquished/daemon/src/shared/VMMain.cpp:61
#7  vmMain (rootSocket=<optimized out>) at Unvanquished/daemon/src/shared/VMMain.cpp:104
#8  0x00005555557f0dce in VM::CreateInProcessNativeVM(std::pair<IPC::Socket, IPC::Socket>, Str::BasicStringRef<char>, VM::VMBase::InProcessInfo&)::$_0::operator()() const (this=0x55555a497428) at Unvanquished/daemon/src/engine/framework/VirtualMachine.cpp:364
#9  std::__invoke_impl<void, VM::CreateInProcessNativeVM(std::pair<IPC::Socket, IPC::Socket>, Str::BasicStringRef<char>, VM::VMBase::InProcessInfo&)::$_0>(std::__invoke_other, VM::CreateInProcessNativeVM(std::pair<IPC::Socket, IPC::Socket>, Str::BasicStringRef<char>, VM::VMBase::InProcessInfo&)::$_0&&) (__f=...) at /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/invoke.h:61
#10 std::__invoke<VM::CreateInProcessNativeVM(std::pair<IPC::Socket, IPC::Socket>, Str::BasicStringRef<char>, VM::VMBase::InProcessInfo&)::$_0>(VM::CreateInProcessNativeVM(std::pair<IPC::Socket, IPC::Socket>, Str::BasicStringRef<char>, VM::VMBase::InProcessInfo&)::$_0&&) (__fn=...) at /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/invoke.h:96
#11 std::thread::_Invoker<std::tuple<VM::CreateInProcessNativeVM(std::pair<IPC::Socket, IPC::Socket>, Str::BasicStringRef<char>, VM::VMBase::InProcessInfo&)::$_0> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x55555a497428) at /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/std_thread.h:292
#12 std::thread::_Invoker<std::tuple<VM::CreateInProcessNativeVM(std::pair<IPC::Socket, IPC::Socket>, Str::BasicStringRef<char>, VM::VMBase::InProcessInfo&)::$_0> >::operator()() (this=0x55555a497428) at /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/std_thread.h:299
#13 std::thread::_State_impl<std::thread::_Invoker<std::tuple<VM::CreateInProcessNativeVM(std::pair<IPC::Socket, IPC::Socket>, Str::BasicStringRef<char>, VM::VMBase::InProcessInfo&)::$_0> > >::_M_run() (this=0x55555a497420) at /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/std_thread.h:244
#14 0x00007ffff72e6333 in std::execute_native_thread_routine (__p=0x55555a497420) at ../../../../../src/libstdc++-v3/src/c++11/thread.cc:104
#15 0x00007ffff6e97ada in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:444
#16 0x00007ffff6f2847c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

Thread 2 (Thread 0x7ffff55146c0 (LWP 273124) "daemon"):
#0  0x00007ffff6ee56f1 in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, req=req@entry=0x7ffff5513a10, rem=rem@entry=0x7ffff5513a10) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:78
#1  0x00007ffff6ef9937 in __GI___nanosleep (req=req@entry=0x7ffff5513a10, rem=rem@entry=0x7ffff5513a10) at ../sysdeps/unix/sysv/linux/nanosleep.c:25
#2  0x00007ffff6f0e2ae in __sleep (seconds=0) at ../sysdeps/posix/sleep.c:55
#3  0x00005555557ece5a in Sys::SignalThread () at Unvanquished/daemon/src/engine/framework/System.cpp:389
#4  0x00007ffff72e6333 in std::execute_native_thread_routine (__p=0x55555679e520) at ../../../../../src/libstdc++-v3/src/c++11/thread.cc:104
#5  0x00007ffff6e97ada in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:444
#6  0x00007ffff6f2847c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

Thread 1 (Thread 0x7ffff5517a80 (LWP 273120) "daemon"):
#0  0x00007ffff6f2a637 in __recvmsg_syscall (flags=0, msg=0x7fffffffd268, fd=32) at ../sysdeps/unix/sysv/linux/recvmsg.c:27
#1  __libc_recvmsg (fd=32, msg=0x7fffffffd268, flags=0) at ../sysdeps/unix/sysv/linux/recvmsg.c:41
#2  0x00005555557f84a8 in NaClReceiveDatagram (handle=32, message=0x7fffffffd340, flags=<optimized out>) at Unvanquished/daemon/libs/nacl/native_client/src/shared/imc/linux/nacl_imc.cc:168
#3  0x00005555557add16 in IPC::InternalRecvMsg (handle=32, reader=...) at Unvanquished/daemon/src/common/IPC/Primitives.cpp:380
#4  0x00005555557ae14b in IPC::Socket::RecvMsg (this=0x555555fae4e0 <cgvm+128>) at Unvanquished/daemon/src/common/IPC/Primitives.cpp:470
#5  0x000055555566d2c0 in IPC::Channel::RecvMsg (this=0x7fffffffd268) at Unvanquished/daemon/src/common/IPC/Channel.h:111
#6  IPC::Channel::RecvReplyMsg (this=0x7fffffffd268) at Unvanquished/daemon/src/common/IPC/Channel.h:121
#7  0x0000555555689f6e in IPC::detail::SendMsg<VM::VMBase::SendMsg<IPC::SyncMessage<IPC::Message<IPC::Id<(unsigned short)0, (unsigned short)3>, int, bool>, IPC::Reply<> >, int&, bool&>(int&, bool&)::{lambda(unsigned int, Util::Reader)#1}&, IPC::Message<IPC::Id<(unsigned short)0, (unsigned short)3>, int, bool>, IPC::Reply<>, int&, bool&>(IPC::Channel&, VM::VMBase::SendMsg<IPC::SyncMessage<IPC::Message<IPC::Id<(unsigned short)0, (unsigned short)3>, int, bool>, IPC::Reply<> >, int&, bool&>(int&, bool&)::{lambda(unsigned int, Util::Reader)#1}&, IPC::SyncMessage<IPC::Message<IPC::Id<(unsigned short)0, (unsigned short)3>, int, bool>, IPC::Reply<> >, int&, bool&) (channel=..., messageHandler=..., args=@0x7fffffffd683: false, args=@0x7fffffffd683: false) at Unvanquished/daemon/src/common/IPC/Channel.h:168
#8  0x000055555567a743 in IPC::SendMsg<IPC::SyncMessage<IPC::Message<IPC::Id<(unsigned short)0, (unsigned short)3>, int, bool>, IPC::Reply<> >, VM::VMBase::SendMsg<IPC::SyncMessage<IPC::Message<IPC::Id<(unsigned short)0, (unsigned short)3>, int, bool>, IPC::Reply<> >, int&, bool&>(int&, bool&)::{lambda(unsigned int, Util::Reader)#1}, int&, bool&>(IPC::Channel&, VM::VMBase::SendMsg<IPC::SyncMessage<IPC::Message<IPC::Id<(unsigned short)0, (unsigned short)3>, int, bool>, IPC::Reply<> >, int&, bool&>(int&, bool&)::{lambda(unsigned int, Util::Reader)#1}&&, int&, bool&) (channel=..., messageHandler=..., args=@0x7fffffffd683: false, args=@0x7fffffffd683: false) at Unvanquished/daemon/src/common/IPC/Channel.h:234
#9  VM::VMBase::SendMsg<IPC::SyncMessage<IPC::Message<IPC::Id<(unsigned short)0, (unsigned short)3>, int, bool>, IPC::Reply<> >, int&, bool&>(int&, bool&) (this=0x555555fae460 <cgvm>, args=@0x7fffffffd683: false, args=@0x7fffffffd683: false) at Unvanquished/daemon/src/engine/framework/VirtualMachine.h:140
#10 CGameVM::CGameDrawActiveFrame (this=0x555555fae460 <cgvm>, serverTime=4733, demoPlayback=false) at Unvanquished/daemon/src/engine/client/cl_cgame.cpp:1000
#11 CL_CGameRendering () at Unvanquished/daemon/src/engine/client/cl_cgame.cpp:655
#12 0x00005555556a6023 in SCR_DrawScreenField () at Unvanquished/daemon/src/engine/client/cl_scrn.cpp:247
#13 0x00005555556a6096 in SCR_UpdateScreen () at Unvanquished/daemon/src/engine/client/cl_scrn.cpp:318
#14 0x000055555569d3c7 in CL_Frame (msec=msec@entry=3) at Unvanquished/daemon/src/engine/client/cl_main.cpp:2094
#15 0x000055555563a55d in Com_Frame () at Unvanquished/daemon/src/engine/qcommon/common.cpp:1029
#16 0x00005555557ec69e in main (argc=<optimized out>, argv=<optimized out>) at Unvanquished/daemon/src/engine/framework/System.cpp:755
```

Here is also a stack trace, with less info, but easier to read at first glance:

```gdb
0x00007fff78fe51b4 in trap_R_AddPolysToScene(int, int, polyVert_t const*, int) () from build/game/default-aocc-lto-reldeb-dll/cgame-native-dll.so

Thread 20 (Thread 0x7fffa10d36c0 (LWP 210629) "daemon"):
#0  0x00007fff78fe51b4 in trap_R_AddPolysToScene(int, int, polyVert_t const*, int) () from build/game/default-aocc-lto-reldeb-dll/cgame-native-dll.so
#1  0x00007fff78f7da17 in CG_AddTrails() () from build/game/default-aocc-lto-reldeb-dll/cgame-native-dll.so
#2  0x00007fff78f84fff in CG_DrawActiveFrame(int, bool) () from build/game/default-aocc-lto-reldeb-dll/cgame-native-dll.so
#3  0x00007fff78f1886c in VM::VMHandleSyscall(unsigned int, Util::Reader) () from build/game/default-aocc-lto-reldeb-dll/cgame-native-dll.so
#4  0x00007fff79014026 in vmMain () from build/game/default-aocc-lto-reldeb-dll/cgame-native-dll.so
#5  0x000055555581f33e in std::thread::_State_impl<std::thread::_Invoker<std::tuple<VM::CreateInProcessNativeVM(std::pair<IPC::Socket, IPC::Socket>, Str::BasicStringRef<char>, VM::VMBase::InProcessInfo&)::$_0> > >::_M_run() ()
#6  0x00007ffff72e6333 in std::execute_native_thread_routine (__p=0x55555757e5d0) at ../../../../../src/libstdc++-v3/src/c++11/thread.cc:104
#7  0x00007ffff6e97ada in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:444
#8  0x00007ffff6f2847c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

Thread 3 (Thread 0x7ffff45ff6c0 (LWP 210594) "daemon"):
#0  0x00007ffff6f2a01f in __libc_accept (fd=4, addr=..., len=0x0) at ../sysdeps/unix/sysv/linux/accept.c:26
#1  0x0000555555817160 in Sys::ReadSingletonSocket() ()
#2  0x00007ffff72e6333 in std::execute_native_thread_routine (__p=0x5555567d18a0) at ../../../../../src/libstdc++-v3/src/c++11/thread.cc:104
#3  0x00007ffff6e97ada in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:444
#4  0x00007ffff6f2847c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

Thread 2 (Thread 0x7ffff55146c0 (LWP 210592) "daemon"):
#0  0x00007ffff6ee56f1 in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, req=req@entry=0x7ffff5513a10, rem=rem@entry=0x7ffff5513a10) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:78
#1  0x00007ffff6ef9937 in __GI___nanosleep (req=req@entry=0x7ffff5513a10, rem=rem@entry=0x7ffff5513a10) at ../sysdeps/unix/sysv/linux/nanosleep.c:25
#2  0x00007ffff6f0e2ae in __sleep (seconds=0) at ../sysdeps/posix/sleep.c:55
#3  0x000055555581951a in Sys::SignalThread() ()
#4  0x00007ffff72e6333 in std::execute_native_thread_routine (__p=0x5555567cd4a0) at ../../../../../src/libstdc++-v3/src/c++11/thread.cc:104
#5  0x00007ffff6e97ada in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:444
#6  0x00007ffff6f2847c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

Thread 1 (Thread 0x7ffff5517a80 (LWP 210581) "daemon"):
#0  0x00007ffff6f2a637 in __recvmsg_syscall (flags=0, msg=0x7fffffffd2b8, fd=32) at ../sysdeps/unix/sysv/linux/recvmsg.c:27
#1  __libc_recvmsg (fd=32, msg=0x7fffffffd2b8, flags=0) at ../sysdeps/unix/sysv/linux/recvmsg.c:41
#2  0x0000555555826e28 in NaClReceiveDatagram ()
#3  0x00005555557d54a1 in IPC::InternalRecvMsg(int, Util::Reader&) ()
#4  0x00005555557d59cb in IPC::Socket::RecvMsg() const ()
#5  0x000055555568f85b in void IPC::detail::SendMsg<VM::VMBase::SendMsg<IPC::SyncMessage<IPC::Message<IPC::Id<(unsigned short)0, (unsigned short)3>, int, bool>, IPC::Reply<> >, int&, bool&>(int&, bool&)::{lambda(unsigned int, Util::Reader)#1}&, IPC::Message<IPC::Id<(unsigned short)0, (unsigned short)3>, int, bool>, IPC::Reply<>, int&, bool&>(IPC::Channel&, VM::VMBase::SendMsg<IPC::SyncMessage<IPC::Message<IPC::Id<(unsigned short)0, (unsigned short)3>, int, bool>, IPC::Reply<> >, int&, bool&>(int&, bool&)::{lambda(unsigned int, Util::Reader)#1}&, IPC::SyncMessage<IPC::Message<IPC::Id<(unsigned short)0, (unsigned short)3>, int, bool>, IPC::Reply<> >, int&, bool&) ()
#6  0x000055555567fcb3 in CL_CGameRendering() ()
#7  0x00005555556ae333 in SCR_DrawScreenField() ()
#8  0x00005555556ae3a6 in SCR_UpdateScreen() ()
#9  0x00005555556a3c57 in CL_Frame(int) ()
#10 0x000055555563c47d in Com_Frame() ()
#11 0x0000555555818cce in main ()
A debugging session is active.
```

And here is another output with other build options:

```
]free(): invalid pointer
malloc(): invalid size (unsorted)
```

Actually those three stacks show complementary informations.

**Comment by illwieckz** [comment]
Well, it's very weird, it segfaults there:

```c++
void trap_R_AddPolysToScene( qhandle_t hShader, int numVerts, const polyVert_t *verts, int numPolys )
{
	std::vector<polyVert_t> myverts(numVerts * numPolys); // ← SEGFAULT
	memcpy(myverts.data(), verts, numVerts * numPolys * sizeof(polyVert_t));
	cmdBuffer.SendMsg<Render::AddPolysToSceneMsg>(hShader, myverts, numVerts, numPolys);
}
```

**Comment by slipher** [comment]
Duplicate of #2682?

**Comment by illwieckz** [comment]
Ah, I forgot this one. It's very likely a duplicate, AOCC is clang-based. AOCC 4.0 is based on Clang 14.0.6 while AOCC 4.1 is based on clang 16.0.3.

**Comment by illwieckz** [comment]
Closed as duplicate of:

- https://github.com/Unvanquished/Unvanquished/issues/2682
