### ISSUE TITLE
Unvanquished crash with bots

### ISSUE THREAD

**Issue by DolceTriade** [Unvanquished/Unvanquished#3037]
# What I did

1. Start `voxelmini` in devmap
2. /bot fill 16 aliens

it crashed

```
Thread 42 "daemon" received signal SIGTRAP, Trace/breakpoint trap.
[Switching to Thread 0x7fffb4c006c0 (LWP 801592)]
0x00007fffcb911234 in BotMaybeAttackWhileClimbing (self=0x7fffc9fa0bd0) at /mnt/media/code/unv-master/src/sgame/sg_bot_nav.cpp:875
875		ASSERT( self->botMind->lastNavconDistance > 0 );
(gdb) bt
#0  0x00007fffcb911234 in BotMaybeAttackWhileClimbing (self=0x7fffc9fa0bd0) at /mnt/media/code/unv-master/src/sgame/sg_bot_nav.cpp:875
#1  0x00007fffcb9103a7 in BotClimbToGoal (self=0x7fffc9fa0bd0) at /mnt/media/code/unv-master/src/sgame/sg_bot_nav.cpp:925
#2  0x00007fffcb9100d7 in BotMoveUpward (self=0x7fffc9fa0bd0, nextCorner=...) at /mnt/media/code/unv-master/src/sgame/sg_bot_nav.cpp:937
#3  0x00007fffcb910f30 in BotTryMoveUpward (self=0x7fffc9fa0bd0) at /mnt/media/code/unv-master/src/sgame/sg_bot_nav.cpp:1040
#4  0x00007fffcb910563 in BotMoveToGoal (self=0x7fffc9fa0bd0) at /mnt/media/code/unv-master/src/sgame/sg_bot_nav.cpp:1097
#5  0x00007fffcb8feeb7 in BotActionRoamInRadius (self=0x7fffc9fa0bd0, node=0x7fff8d0f2740) at /mnt/media/code/unv-master/src/sgame/sg_bot_ai.cpp:1126
#6  0x00007fffcb8fc739 in BotEvaluateNode (self=0x7fffc9fa0bd0, node=0x7fff8d0f2740) at /mnt/media/code/unv-master/src/sgame/sg_bot_ai.cpp:602
#7  0x00007fffcb8fc698 in BotSelectorNode (self=0x7fffc9fa0bd0, node=0x7fff8d0fc370) at /mnt/media/code/unv-master/src/sgame/sg_bot_ai.cpp:276
#8  0x00007fffcb8fc739 in BotEvaluateNode (self=0x7fffc9fa0bd0, node=0x7fff8d0fc370) at /mnt/media/code/unv-master/src/sgame/sg_bot_ai.cpp:602
#9  0x00007fffcb8fcad9 in BotSequenceNode (self=0x7fffc9fa0bd0, node=0x7fff8d0fc220) at /mnt/media/code/unv-master/src/sgame/sg_bot_ai.cpp:334
#10 0x00007fffcb8fc739 in BotEvaluateNode (self=0x7fffc9fa0bd0, node=0x7fff8d0fc220) at /mnt/media/code/unv-master/src/sgame/sg_bot_ai.cpp:602
#11 0x00007fffcb8fc698 in BotSelectorNode (self=0x7fffc9fa0bd0, node=0x7fff8d0fc000) at /mnt/media/code/unv-master/src/sgame/sg_bot_ai.cpp:276
#12 0x00007fffcb8fc739 in BotEvaluateNode (self=0x7fffc9fa0bd0, node=0x7fff8d0fc000) at /mnt/media/code/unv-master/src/sgame/sg_bot_ai.cpp:602
#13 0x00007fffcb8fcad9 in BotSequenceNode (self=0x7fffc9fa0bd0, node=0x7fff8d0f7bd0) at /mnt/media/code/unv-master/src/sgame/sg_bot_ai.cpp:334
#14 0x00007fffcb8fc739 in BotEvaluateNode (self=0x7fffc9fa0bd0, node=0x7fff8d0f7bd0) at /mnt/media/code/unv-master/src/sgame/sg_bot_ai.cpp:602
#15 0x00007fffcb8fc698 in BotSelectorNode (self=0x7fffc9fa0bd0, node=0x7fff8d0f7b10) at /mnt/media/code/unv-master/src/sgame/sg_bot_ai.cpp:276
#16 0x00007fffcb8fc739 in BotEvaluateNode (self=0x7fffc9fa0bd0, node=0x7fff8d0f7b10) at /mnt/media/code/unv-master/src/sgame/sg_bot_ai.cpp:602
#17 0x00007fffcb8fd079 in BotBehaviorNode (self=0x7fffc9fa0bd0, node=0x7fff8d0f7aa0) at /mnt/media/code/unv-master/src/sgame/sg_bot_ai.cpp:580
#18 0x00007fffcb8fc739 in BotEvaluateNode (self=0x7fffc9fa0bd0, node=0x7fff8d0f7aa0) at /mnt/media/code/unv-master/src/sgame/sg_bot_ai.cpp:602
#19 0x00007fffcb8fcf0c in BotConditionNode (self=0x7fffc9fa0bd0, node=0x7fff8d0f9870) at /mnt/media/code/unv-master/src/sgame/sg_bot_ai.cpp:558
#20 0x00007fffcb8fc739 in BotEvaluateNode (self=0x7fffc9fa0bd0, node=0x7fff8d0f9870) at /mnt/media/code/unv-master/src/sgame/sg_bot_ai.cpp:602
#21 0x00007fffcb8fc698 in BotSelectorNode (self=0x7fffc9fa0bd0, node=0x7fff8d0f47c0) at /mnt/media/code/unv-master/src/sgame/sg_bot_ai.cpp:276
#22 0x00007fffcb8fc739 in BotEvaluateNode (self=0x7fffc9fa0bd0, node=0x7fff8d0f47c0) at /mnt/media/code/unv-master/src/sgame/sg_bot_ai.cpp:602
#23 0x00007fffcb8fd079 in BotBehaviorNode (self=0x7fffc9fa0bd0, node=0x7fff8d0f7f40) at /mnt/media/code/unv-master/src/sgame/sg_bot_ai.cpp:580
#24 0x00007fffcb9053b9 in G_BotThink (self=0x7fffc9fa0bd0) at /mnt/media/code/unv-master/src/sgame/sg_bot.cpp:505
#25 0x00007fffcb8c2b46 in ClientTimerActions (ent=0x7fffc9fa0bd0, msec=25) at /mnt/media/code/unv-master/src/sgame/sg_active.cpp:927
#26 0x00007fffcb8bff71 in ClientThink_real (self=0x7fffc9fa0bd0) at /mnt/media/code/unv-master/src/sgame/sg_active.cpp:2275
#27 0x00007fffcb8c004f in G_RunClient (ent=0x7fffc9fa0bd0) at /mnt/media/code/unv-master/src/sgame/sg_active.cpp:2323
#28 0x00007fffcb97c7bd in G_RunFrame (levelTime=74150) at /mnt/media/code/unv-master/src/sgame/sg_main.cpp:2319
#29 0x00007fffcb8f5517 in VM::VMHandleSyscall(unsigned int, Util::Reader)::$_9::operator()(int) const (this=0x7fffb4bff867, levelTime=74150) at /mnt/media/code/unv-master/src/sgame/sg_api.cpp:133
#30 0x00007fffcb8f54ec in Util::apply_impl<VM::VMHandleSyscall(unsigned int, Util::Reader)::$_9, std::tuple<int&&>, 0ul>(VM::VMHandleSyscall(unsigned int, Util::Reader)::$_9&&, std::tuple<int&&>&&, Util::seq<0ul>) (func=..., tuple=...)
```

**Comment by DolceTriade** [comment]
```
print self->botMind->lastNavconDistance 
$1 = -118
```

**Comment by DolceTriade** [comment]
```
diff --git a/src/sgame/botlib/bot_nav.cpp b/src/sgame/botlib/bot_nav.cpp
index b9f9f3012..039374383 100644
--- a/src/sgame/botlib/bot_nav.cpp
+++ b/src/sgame/botlib/bot_nav.cpp
@@ -287,11 +287,7 @@ void G_BotUpdatePath( int botClientNum, const botRouteTarget_t *target, botNavCm
 				glm::vec3 ownPos = VEC2GLM( self->s.origin );
 				// HACK: if the bot wants to move upward, make the distance
 				// positive, make it negative otherwise
-				self->botMind->lastNavconDistance = glm::distance( ownPos , nextCorner );
-				if ( nextCorner.z - ownPos.z < 0 )
-				{
-					self->botMind->lastNavconDistance = -self->botMind->lastNavconDistance;
-				}
+				self->botMind->lastNavconDistance = fabs( glm::distance( ownPos , nextCorner ) );
 			}
 		}
 
```

This patch is sufficient to work around the issue for me, but I don't know if its correct. I'll play with it to see if I notice any regressions.

**Comment by slipher** [comment]
I think this is a duplicate of #3002. I never got the assertion to trigger though: I just found it by reading code. But then I develop in RelWithDebInfo mode the majority of the time.

**Comment by DolceTriade** [comment]
it is indeed
