### ISSUE TITLE
some server option can segfault the client

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#602]
Hi, I know it does not make sense to to that, but using an option like `+set server.lanOnly true` on client does a segfault:

```gdb
$ LANG=C unvanquished --gdb +nocurses +set server.lanOnly true
(gdb) r
Starting program: /usr/lib/games/unvanquished/unvanquished +set fs_libpath /usr/lib/games/unvanquished +set fs_basepath /var/games/unvanquished +nocurses +set server.lanOnly true
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Unvanquished 0.36.0 Linux x86_64 Feb  2 2015
+set fs_libpath /usr/lib/games/unvanquished +set fs_basepath /var/games/unvanquished +set server.lanOnly true  
]
Program received signal SIGSEGV, Segmentation fault.
strlen () at ../sysdeps/x86_64/strlen.S:106
106	../sysdeps/x86_64/strlen.S: No such file or directory.
(gdb) bt
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
#1  0x00000000004521b0 in length (__s=0x0) at /usr/include/c++/4.9/bits/char_traits.h:263
#2  BasicStringRef (other=0x0, this=<optimized out>) at /tmp/buildd/unvanquished-0.36.0/src/common/String.h:50
#3  Com_StartupVariable (match=match@entry=0x6be557 "developer") at /tmp/buildd/unvanquished-0.36.0/src/engine/qcommon/common.cpp:478
#4  0x0000000000452428 in Com_Init (commandLine=commandLine@entry=0x7fffffffdd80 "") at /tmp/buildd/unvanquished-0.36.0/src/engine/qcommon/common.cpp:1802
#5  0x000000000041a795 in main (argc=<optimized out>, argv=<optimized out>) at /tmp/buildd/unvanquished-0.36.0/src/engine/sys/sys_main.cpp:657
```

**Comment by Viech** [comment]
Poking @Kangz.
