### ISSUE TITLE
main window not visible

### ISSUE THREAD

**Issue by hasufell** [Unvanquished/Unvanquished#887]
When starting unvanquished, I hear sound and the console shows stuff, but the main window is not there. Probably bad window handling.

```
$ unvanquished
Unvanquished 0.47 Linux x86_64 Jan 13 2016
cmdline: -pakpath /usr/share/unvanquished/pkg -libpath /usr/lib64/unvanquished
Lib path: /usr/lib64/unvanquished 
Home path: /home/jule/.unvanquished 
Pak search path: /usr/share/unvanquished/pkg 
Pak search path: /home/jule/.unvanquished/pkg 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.47.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.46.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.45.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.44.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.43.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.42.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.41.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.40.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.39.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.38.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.37.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.36.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.35.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.34.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.33.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.32.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.31.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.30.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.29.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.28.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.27.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.26.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.25.0.pk3'... 
execing 'default.cfg' 
Warn: Couldn't read conhistory: No such file or directory 
Loaded 9 languages 
Set language to English 
----- Client Initialization ----- 
Loading RSA keys from pubkey 
Daemon RSA public-key file not found, regenerating 
Regenerating RSA keypair; writing to pubkey 
Daemon RSA keys generated 
----- Client Initialization Complete ----- 
Calling GetRefAPI… 
SDL_Init( SDL_INIT_VIDEO )...  
Using SDL Version 2.0.3 
SDL using driver "x11" 
Initializing OpenGL display 
Display aspect: 3.200 
...setting mode -2: 
 3840 1200 
The change will take effect after restart. 
The change will take effect after restart. 
Using 24 Color bits, 24 depth, 8 stencil display. 
Using GLEW 1.10.0 
Using enhanced (GL3) Renderer in GL 3.x mode... 
Available modes: '3840x1200 1280x720 1366x768 1280x800 1440x900 1680x1050 1920x1200 640x480 ' 
GL_RENDERER: GeForce GTX 750 Ti/PCIe/SSE2 
Detected graphics driver class 'OpenGL 3+' 
Detected graphics hardware class 'generic' 
Initializing OpenGL extensions 
...ignoring GL_ARB_debug_output 
...using GL_ARB_fragment_shader 
...using GL_ARB_vertex_shader 
...using GL_ARB_shading_language_100 
...found shading language version 450 
...using GL_ARB_depth_texture 
...using GL_ARB_texture_cube_map 
...using GL_ARB_half_float_pixel 
...using GL_ARB_texture_float 
...using GL_ARB_texture_rg 
...using GL_EXT_packed_depth_stencil 
...ignoring GL_ARB_texture_compression 
...ignoring GL_EXT_texture_compression_s3tc 
...using GL_ARB_texture_non_power_of_two 
...using GL_SGIS_generate_mipmap 
...using GL_EXT_texture_filter_anisotropic 
...using GL_ARB_vertex_buffer_object 
...using GL_ARB_half_float_vertex 
...using GL_ARB_framebuffer_object 
...using GL_ARB_shader_objects 
...using GL_ARB_occlusion_query 
...using GL_ARB_draw_buffers 
...GL_GREMEDY_string_marker not found 
...using GL_ARB_get_program_binary 
...using GL_ARB_buffer_storage 
...using GL_ARB_map_buffer_range 
...using GL_ARB_sync 
glsl shaders took 1978 msec to build


GL_VENDOR: NVIDIA Corporation 
GL_RENDERER: GeForce GTX 750 Ti/PCIe/SSE2 
GL_VERSION: 4.5.0 NVIDIA 355.11 
GL_SHADING_LANGUAGE_VERSION: 4.50 NVIDIA 
GL_MAX_VERTEX_UNIFORM_COMPONENTS 4096 
Using OpenGL 3.x context 
Using GPU vertex skinning with max 233 bones in a single pass 
Extracting VM module cgame-x86_64.nexe from /usr/share/unvanquished/pkg/unvanquished_0.47.0.pk3... 
Loading VM module cgame-x86_64.nexe... 
][16565,2011801408:16:18:19.367549] Native Client module will be loaded at base address 0x00004f5f00000000
Loaded VM module in 68 msec 
INFO: Loading Lua interpreter 
INFO: Loaded font face Roboto Bold (from fonts/Roboto-Bold.ttf). 
INFO: Loaded font face Roboto Bold Italic (from fonts/Roboto-BoldItalic.ttf). 
INFO: Loaded font face Roboto Italic (from fonts/Roboto-Italic.ttf). 
INFO: Loaded font face Roboto Regular (from fonts/Roboto-Regular.ttf). 
INFO: Loaded font face FontAwesome Regular (from fonts/fontawesome-webfont.ttf). 
INFO: Loaded font face DejaVu Sans Condensed (from fonts/DejaVuSansCondensed.ttf). 
INFO: Loaded font face Material Icons Regular (from fonts/MaterialIcons-Regular.ttf). 
--- Common Initialization Complete --- 
IP: 127.0.0.1 
IP: 192.168.0.12 
IP: 172.17.0.1 
Opening IP6 socket: [::]:* 
Opening IP socket: 0.0.0.0:* 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.47.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.46.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.45.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.44.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.43.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.42.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.41.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.40.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.39.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.38.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.37.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.36.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.35.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.34.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.33.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.32.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.31.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.30.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.29.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.28.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.27.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.26.0.pk3'... 
Loading pak '/usr/share/unvanquished/pkg/unvanquished_0.25.0.pk3'... 
```

**Comment by DolceTriade** [comment]
Could you try running
```unvanquished -set r_mode 16```

**Comment by hasufell** [comment]
that yields a similar log with the difference of `Error: Crashed with signal 11: Segmentation fault`

**Comment by DolceTriade** [comment]
Wow. Would this be a build compiled from source? Could we get a backtrace?

**Comment by hasufell** [comment]
```
Program received signal SIGSEGV, Segmentation fault.
0x000000000080527c in RB_StretchPic (data=0x7fffcef1e040)
    at /var/tmp/paludis/games-fps-unvanquished-0.47.0/work/unvanquished-0.47.0/daemon/src/engine/renderer/tr_backend.cpp:4879
4879		tess.verts[ numVerts ].xyz[ 0 ] = cmd->x;
(gdb) bt
#0  0x000000000080527c in RB_StretchPic (data=0x7fffcef1e040)
    at /var/tmp/paludis/games-fps-unvanquished-0.47.0/work/unvanquished-0.47.0/daemon/src/engine/renderer/tr_backend.cpp:4879
#1  0x0000000000807a57 in RB_ExecuteRenderCommands (data=0x7fffcef1e040)
    at /var/tmp/paludis/games-fps-unvanquished-0.47.0/work/unvanquished-0.47.0/daemon/src/engine/renderer/tr_backend.cpp:5646
#2  0x000000000081d1d1 in R_IssueRenderCommands (runPerformanceCounters=true)
    at /var/tmp/paludis/games-fps-unvanquished-0.47.0/work/unvanquished-0.47.0/daemon/src/engine/renderer/tr_cmds.cpp:183
#3  0x000000000081e360 in RE_EndFrame (frontEndMsec=0x0, backEndMsec=0x0)
    at /var/tmp/paludis/games-fps-unvanquished-0.47.0/work/unvanquished-0.47.0/daemon/src/engine/renderer/tr_cmds.cpp:846
#4  0x000000000079f888 in SCR_UpdateScreen () at /var/tmp/paludis/games-fps-unvanquished-0.47.0/work/unvanquished-0.47.0/daemon/src/engine/client/cl_scrn.cpp:373
#5  0x0000000000795abf in CL_Frame (msec=10) at /var/tmp/paludis/games-fps-unvanquished-0.47.0/work/unvanquished-0.47.0/daemon/src/engine/client/cl_main.cpp:3060
#6  0x00000000006cc66d in Com_Frame () at /var/tmp/paludis/games-fps-unvanquished-0.47.0/work/unvanquished-0.47.0/daemon/src/engine/qcommon/common.cpp:1911
#7  0x00000000007a04dd in Application::ClientApplication::Frame (this=0x1554c20 <Application::GetApp()::app>)
    at /var/tmp/paludis/games-fps-unvanquished-0.47.0/work/unvanquished-0.47.0/daemon/src/engine/client/ClientApplication.cpp:80
#8  0x00000000008eb816 in Application::Frame () at /var/tmp/paludis/games-fps-unvanquished-0.47.0/work/unvanquished-0.47.0/daemon/src/engine/framework/Application.cpp:75
#9  0x0000000000924370 in main (argc=8, argv=0x7fffffffd348)
    at /var/tmp/paludis/games-fps-unvanquished-0.47.0/work/unvanquished-0.47.0/daemon/src/engine/framework/System.cpp:678
```

**Comment by DolceTriade** [comment]
Absolutely confused why this would happen. Cannot reproduce this on nvidia hardware.

**Comment by Viech** [comment]
Summoning the renderer wizards: @gimhael, @cmf028.

**Comment by illwieckz** [comment]
We couldn't reproduce for 5 years, and the code creating the window got multiple rewrite. Better reopen or create new issue if is seen again.
